name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: should it be skipped?
        env:
          COMMIT_FILTER: "ci-skip"
        run: |
          # Get last commit message
          readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
          echo "last commit log: $last_commit_log"

          readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )
          echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

          if [[ "$filter_count" -eq 0 ]]; then
            echo "all good, continue"
          else
            echo "the last commit log \"$last_commit_log\" contains \"$COMMIT_FILTER\", stopping"
            exit 78
          fi
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Plugin
        uses: actions/upload-artifact@master
        with:
          name: Plugin
          path: ./Plugin/target/
      - name: Upload Legacy Support
        uses: actions/upload-artifact@master
        with:
          name: Legacy Support
          path: ./Addon/LegacySupport/target/
